### ISSUE TITLE
Mini To-do

### ISSUE THREAD

**Issue by gugoan** [gugoan/economizzer#18]
- [x] File upload
- [x] Initial dashboard
- [x] Totals on gridview
- [x] Some datepicker
- [x] Filter by date, range
- [x] Login | User autentication
- [x] Multiuser | indepent user data separation
- [x] Translation | Multi front-end language select for user
- [ ] Open attachment (if exist)
- [ ] Fix value with decimals
- [ ] Subcat | Categories with sub-categories
- [ ] Option after a release, add another
- [ ] Goals | Insert goals and reports

**Comment by gugoan** [comment]
separate issues.
